name: 'Docker Build and Deploy to Container Registry'
description: 'Builds a Docker Container, pushes to Registry'
inputs:
  REGISTRY_LOGIN_SERVER:
    description: 'Container Registry URL'
    required: true
  REGISTRY_USERNAME:
    description: 'Registry Username'
    required: true
  REGISTRY_PASSWORD:
    description: 'Registry Password'
    required: true
  IMAGE_NAME:
    description: 'Repository/Image Name'
    required: true
  IMAGE_TAG:
    description: 'Tag for the image'
    required: false
    default: 'latest'
  FUNC_APP_NAME:
    description: 'The Azure Function App name'
    required: true
  # Added input for Azure Authentication
  AZURE_CREDENTIALS:
    description: 'JSON object containing Service Principal credentials'
    required: false
  PROJECT_PATH:
    description: 'Subdirectory of the React app'
    required: false
    default: 'appcode/backend/my-app'

runs:
  using: "composite"
  steps:
    - name: Azure Login
      if: ${{ inputs.AZURE_CREDENTIALS != '' }}
      uses: azure/login@v2 
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Function
      uses: Azure/functions-container-action@v1
      with:
        app-name: ${{ inputs.FUNC_APP_NAME }}
        image: ${{ env.FULL_IMAGE_PATH }}
