name: 'Web App Deploy'
description: 'Deploys code onto App Service, Web, or Function App'
inputs:
  TARGET_ENVIRONMENT:
    description: 'Target environment (nonprod, prod)'
    required: true
  CHECKOUT_PATH:
    description: 'Path for checkout'
    required: false
    default: '.'
  WORKING_DIRECTORY:
    description: 'Root of terraform src'
    required: true
  REGION:
    description: 'Azure Region'
    required: true
  DESTROY:
    description: 'Destroy resources'
    required: false
    default: 'false'
  PACKAGE_PATH:
    description: 'Path to the code package to deploy'
    required: false
    default: '.'
  DEPLOY_TARGET_NAME:
    description: 'Name of the specific App Service/Function to deploy code to'
    required: false

runs:
  using: "composite"
  steps:
    - name: Determine Target App Name
      id: target
      shell: bash
      run: |
        if [ -n "${{ inputs.DEPLOY_TARGET_NAME }}" ]; then
          echo "name=${{ inputs.DEPLOY_TARGET_NAME }}" >> $GITHUB_OUTPUT
        fi

    - name: Debug Deployment Inputs
      shell: bash
      run: |
        echo "Deploying to: ${{ steps.target.outputs.name }}"
        echo "Images Input: '${{ inputs.IMAGES }}'"

    - name: Deploy Container to Web/Function App
      if: inputs.DESTROY != 'true' && inputs.IMAGES != ''
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.target.outputs.name }}
        images: ${{ inputs.IMAGES }}

    - name: Deploy Code to Web/Function App
      if: inputs.DESTROY != 'true' && inputs.IMAGES == ''
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.target.outputs.name }}
        package: ${{ inputs.PACKAGE_PATH }}