name: 'Terraform Deploy'
description: 'Runs terraform init, plan, and apply dynamically'
inputs:
  TF_VERSION:
    description: 'The Terraform version to use'
    required: false 
    default: 1.13.4 
  TARGET_ENVIRONMENT:
    description: 'The target environment to deploy towards (dev, uat, prod)'
    required: true
  CHECKOUT_PATH:
    description: 'The path of where to checkout the terraform`'
    required: false 
  WORKING_DIRECTORY:
    description: 'The path of where to build terraform from`'
    required: false 

runs:
    using: "composite"
    steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.TF_VERSION }}


    - name: deploy terraform
      shell: bash
      working-directory: ${{ inputs.CHECKOUT_PATH }}/${{ inputs.WORKING_DIRECTORY }}
      run: |
        terraform init --backend-config=${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfbackend

        echo "Running terraform plan..."
        terraform plan -var-file="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfvars" -out=tflan

        echo "Running terraform apply..."
        terraform apply -auto-approve tfplan
      