name: 'Terraform Deploy'
description: 'Runs terraform init, plan, and apply dynamically'
inputs:
  TF_VERSION:
    description: 'The Terraform version to use'
    required: false 
    default: "1.14.3" # Updated to latest 2026 version
  TARGET_ENVIRONMENT:
    description: 'Target environment (nonprod, prod)'
    required: true
  CHECKOUT_PATH:
    description: 'Path for checkout'
    required: false
    default: '.'
  WORKING_DIRECTORY:
    description: 'Root of terraform src'
    required: true
  REGION:
    description: 'Azure Region'
    required: true
  DESTROY:
    description: 'Destroy resources'
    required: false
    default: 'false'
  FUNCAPP_NAME:
    description: 'Name of the Function App'
    required: false
  WEBAPP_NAME:
    description: 'Name of the Web App'
    required: false

runs:
  using: "composite"
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v3 # Updated to v3
      with:
        terraform_version: ${{ inputs.TF_VERSION }}

    - name: deploy terraform
      shell: bash
      working-directory: ${{ inputs.CHECKOUT_PATH }}/${{ inputs.WORKING_DIRECTORY }}
      env:
        TF_VAR_primary_region: ${{ inputs.REGION }}
      run: |
        # Use -reconfigure to ensure backend stays fresh
        terraform init -reconfigure -backend-config="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfbackend"

        # Construct var arguments if RESOURCE_NAME is provided
        VAR_ARGS=""
        if [ -n "${{ inputs.FUNCAPP_NAME }}" ]; then
          VAR_ARGS="$VAR_ARGS -var funcapp_name=${{ inputs.FUNCAPP_NAME }}"
        fi
        if [ -n "${{ inputs.WEBAPP_NAME }}" ]; then
          VAR_ARGS="$VAR_ARGS -var webapp_name=${{ inputs.WEBAPP_NAME }}"
        fi

        if [ "${{ inputs.DESTROY }}" == "true" ]; then
          echo "Running terraform DESTROY plan..."
          terraform plan -destroy -var-file="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfvars" $VAR_ARGS -out=tfplan
        else
          echo "Running terraform plan..."
          # Fixed typo: changed -out=tflan to -out=tfplan
          terraform plan -var-file="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfvars" $VAR_ARGS -out=tfplan
        fi

        echo "Running terraform apply (or destroy)..."
        terraform apply -auto-approve tfplan
