name: 'Terraform Deploy'
description: 'Runs terraform init, plan, and apply dynamically'
inputs:
  TF_VERSION:
    description: 'The Terraform version to use'
    required: false 
    default: "1.14.3" # Updated to latest 2026 version
  TARGET_ENVIRONMENT:
    description: 'Target environment (nonprod, prod)'
    required: true
  CHECKOUT_PATH:
    description: 'Path for checkout'
    required: false
    default: '.'
  WORKING_DIRECTORY:
    description: 'Root of terraform src'
    required: true
  REGION:
    description: 'Azure Region'
    required: true
  DESTROY:
    description: 'Destroy resources'
    required: false
    default: 'false'
  FUNCAPP_NAME:
    description: 'Name of the Function App'
    required: false
  WEBAPP_NAME:
    description: 'Name of the Web App'
    required: false
  IMAGE_TAG:
    description: 'Tag for the Docker Image'
    required: false
    default: 'latest'

outputs:
  webapp_name:
    description: "The name of the webapp from terraform output"
    value: ${{ steps.tf_outputs.outputs.webapp_name }}
  funcapp_name:
    description: "The name of the funcapp from terraform output"
    value: ${{ steps.tf_outputs.outputs.funcapp_name }}

runs:
  using: "composite"
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v3 # Updated to v3
      with:
        terraform_version: ${{ inputs.TF_VERSION }}

    - name: deploy terraform
      shell: bash
      working-directory: ${{ inputs.CHECKOUT_PATH }}/${{ inputs.WORKING_DIRECTORY }}
      env:
        TF_VAR_funcapp_name: ${{ inputs.FUNCAPP_NAME }}
        TF_VAR_webapp_name: ${{ inputs.WEBAPP_NAME }}
        TF_VAR_image_tag: ${{ inputs.IMAGE_TAG }}
      run: |
        # Use -reconfigure to ensure backend stays fresh
        terraform init -reconfigure -backend-config="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfbackend"

        # Construct var arguments (CLI -var overrides tfvars)
        VAR_ARGS="-var primary_region=${{ inputs.REGION }}"

        # Pass environment variables as -var to override tfvars
        if [ -n "$TF_VAR_secondary_region" ]; then
          VAR_ARGS="$VAR_ARGS -var secondary_region=$TF_VAR_secondary_region"
        fi
        if [ -n "$TF_VAR_shouldBeMultiRegion" ]; then
          VAR_ARGS="$VAR_ARGS -var shouldBeMultiRegion=$TF_VAR_shouldBeMultiRegion"
        fi

        if [ "${{ inputs.DESTROY }}" == "true" ]; then
          echo "Running terraform DESTROY plan..."
          terraform plan -destroy -var-file="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfvars" $VAR_ARGS -out=tfplan
        else
          echo "Running terraform plan..."
          # Fixed typo: changed -out=tflan to -out=tfplan
          terraform plan -var-file="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfvars" $VAR_ARGS -out=tfplan
        fi

        echo "Running terraform apply (or destroy)..."
        terraform apply -auto-approve tfplan

    - name: Get Terraform Outputs
      id: tf_outputs
      shell: bash
      working-directory: ${{ inputs.CHECKOUT_PATH }}/${{ inputs.WORKING_DIRECTORY }}
      run: |
        echo "webapp_name=$(terraform output -raw webapp_name 2>/dev/null || echo '')" >> $GITHUB_OUTPUT
        echo "funcapp_name=$(terraform output -raw funcapp_name 2>/dev/null || echo '')" >> $GITHUB_OUTPUT
