name: 'Terraform Deploy'
description: 'Runs terraform init, plan, and apply dynamically'
inputs:
  TF_VERSION:
    description: 'The Terraform version to use'
    required: false 
    default: "1.14.3" # Updated to latest 2026 version
  TARGET_ENVIRONMENT:
    description: 'Target environment (nonprod, prod)'
    required: true
  CHECKOUT_PATH:
    description: 'Path for checkout'
    required: false
    default: '.'
  WORKING_DIRECTORY:
    description: 'Root of terraform src'
    required: true

runs:
  using: "composite"
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v3 # Updated to v3
      with:
        terraform_version: ${{ inputs.TF_VERSION }}

    - name: deploy terraform
      shell: bash
      working-directory: ${{ inputs.CHECKOUT_PATH }}/${{ inputs.WORKING_DIRECTORY }}
      run: |
        # Use -reconfigure to ensure backend stays fresh
        terraform init -reconfigure -backend-config="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfbackend"

        echo "Running terraform plan..."
        # Fixed typo: changed -out=tflan to -out=tfplan
        terraform plan -var-file="${{ inputs.TARGET_ENVIRONMENT }}/terraform.tfvars" -out=tfplan

        echo "Running terraform apply..."
        #terraform apply -auto-approve tfplan
