name: 'React App Service Deploy'
description: 'Builds a React Application and Deploys it onto Azure App Service'
inputs:
  APP_SVC_NAME:
    description: 'The App Service name'
    required: true
  TARGET_ENVIRONMENT:
    description: 'The target environment (nonprod, prod)'
    required: true
  NODE_VERSION:
    description: 'Node version'
    required: false
    default: "22.x"
  PROJECT_PATH:
    description: 'Subdirectory of the React app'
    required: false
    default: 'appcode/frontend/my-app'

runs:
    using: "composite"
    steps:
        - name: setting up node
          uses: actions/setup-node@v4 
          with:
            node-version: ${{ inputs.NODE_VERSION }}
            cache-dependency-path: ${{ inputs.PROJECT_PATH }}/package-lock.json

        - name: install dependencies
          shell: bash
          run: npm install 
          working-directory: ${{ inputs.PROJECT_PATH }}

        - name: build 
          shell: bash
          run: |
            echo "building react app"
            npm run build  
          working-directory: ${{ inputs.PROJECT_PATH }}

        - name: deploy to azure
          uses: azure/webapps-deploy@v3 
          with:
            app-name: ${{ inputs.APP_SVC_NAME }}
            package: '${{ inputs.PROJECT_PATH }}/build' 
