CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    dob TEXT,
    role TEXT,
    hire_date TEXT,
    manager TEXT
);

INSERT INTO employees (name, address, dob, role, hire_date, manager)
VALUES 
('Alice Smith', '123 Maple St, FL', '1990-05-15', 'Software Engineer', '2020-01-15', 'Bob Jones'),
('Bob Jones', '456 Oak Ave, NY', '1985-11-22', 'Engineering Manager', '2015-03-10', NULL);
