name: 'Docker Build and Deploy to Container Registry'
description: 'Builds a Docker Container, pushes to Registry'
inputs:
  REGISTRY_LOGIN_SERVER:
    description: 'Container Registry URL'
    required: true
  REGISTRY_USERNAME:
    description: 'Registry Username'
    required: true
  REGISTRY_PASSWORD:
    description: 'Registry Password'
    required: true
  IMAGE_NAME:
    description: 'Repository/Image Name'
    required: true
  IMAGE_TAG:
    description: 'Tag for the image'
    required: false
    default: 'latest'
  AZURE_CREDENTIALS:
    description: 'JSON object containing Service Principal credentials'
    required: false
  PROJECT_PATH:
    description: 'Subdirectory of the app containing the Dockerfile'
    required: false
  BUILD_ARGS:
    description: 'List of build-time variables (e.g., REACT_APP_API_URL=...)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Azure Login
      if: ${{ inputs.AZURE_CREDENTIALS != '' }}
      uses: azure/login@v2 
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.REGISTRY_USERNAME }}
        password: ${{ inputs.REGISTRY_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.PROJECT_PATH }}
        file: ${{ inputs.PROJECT_PATH }}/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ inputs.REGISTRY_USERNAME }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
        build-args: ${{ inputs.BUILD_ARGS }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
